In [8]:
from azimuth import az

In [13]:
az.crypto.candles('BTC/USDT', provider="binance", interval="1h", start_date="2024-10-08", end_date="2024-10-08").to_df()

,date,open,high,low,close,volume,value
0,2024-10-08 00:00:00+03:00,63020.00,63374.00,63002.29,63373.99,399.72130,2.527667e+07
1,2024-10-08 01:00:00+03:00,63373.99,63374.00,62419.90,62471.08,1024.37163,6.437782e+07
2,2024-10-08 02:00:00+03:00,62471.08,62665.83,62128.00,62224.00,1359.66669,8.485229e+07
3,2024-10-08 03:00:00+03:00,62224.01,62585.06,62156.02,62552.98,795.16170,4.959672e+07
4,2024-10-08 04:00:00+03:00,62552.98,62737.84,62312.00,62630.01,699.78371,4.376300e+07
5,2024-10-08 05:00:00+03:00,62630.01,62789.65,62419.90,62785.78,790.25190,4.946995e+07
6,2024-10-08 06:00:00+03:00,62785.79,62820.00,62522.61,62629.80,473.99204,2.970191e+07
7,2024-10-08 07:00:00+03:00,62629.80,62778.04,62533.56,62694.90,567.31828,3.555647e+07
8,2024-10-08 08:00:00+03:00,62694.90,62723.69,62305.78,62517.35,719.31657,4.495193e+07
9,2024-10-08 09:00:00+03:00,62517.35,62531.52,62200.00,62509.42,580.02424,3.617911e+07
10,2024-10-08 10:00:00+03:00,62509.42,62509.42,62005.00,62319.99,722.21187,4.492648e+07
11,2024-10-08 11:00:00+03:00,62319.99,62439.32,62193.63,62409.46,824.81768,5.141458e+07
12,2024-10-08 12:00:00+03:00,62409.46,62590.00,62301.14,62537.38,524.50951,3.274828e+07
13,2024-10-08 13:00:00+03:00,62537.37,62589.86,62410.82,62519.78,406.80723,2.543096e+07
14,2024-10-08 14:00:00+03:00,62519.77,62670.16,62471.24,62624.01,484.82065,3.034004e+07
15,2024-10-08 15:00:00+03:00,62624.02,62670.00,62427.15,62440.00,463.54487,2.899065e+07
16,2024-10-08 16:00:00+03:00,62440.01,63058.43,62326.52,63035.27,1568.71636,9.834110e+07
17,2024-10-08 17:00:00+03:00,63035.27,63200.00,62157.46,62778.00,2396.82105,1.500374e+08
18,2024-10-08 18:00:00+03:00,62778.00,62850.24,61864.89,62288.01,2548.14024,1.589367e+08
19,2024-10-08 19:00:00+03:00,62288.01,62598.00,62023.42,62570.00,889.56934,5.543861e+07
20,2024-10-08 20:00:00+03:00,62569.99,62570.00,62071.31,62393.94,716.71801,4.465206e+07
21,2024-10-08 21:00:00+03:00,62393.94,62534.00,61930.34,62110.72,928.34993,5.775993e+07
22,2024-10-08 22:00:00+03:00,62110.71,62350.00,61860.31,62329.99,1013.87589,6.294666e+07

In [12]:
az.crypto.candles('BTC/USDT', provider="binance", interval="1d", start_date="2024-10-07", end_date="2024-10-08").to_df()

,date,open,high,low,close,volume,value
0,2024-10-07 03:00:00+03:00,62819.91,64478.19,62128.00,62224.0,25966.18520,1.646316e+09
1,2024-10-08 03:00:00+03:00,62224.01,63200.00,61860.31,62320.0,18114.45645,1.131164e+09