In [1]:
from azimuth import az

In [2]:
az.crypto.candles('BTC/USDT', provider="bybit", interval="1h", start_date="2024-10-08", end_date="2024-10-08").to_df()

,date,open,high,low,close,volume,value
0,2024-10-08 00:00:00,63026.40,63378.38,63001.51,63378.38,300.137136,1.897337e+07
1,2024-10-08 01:00:00,63378.38,63378.38,62409.90,62457.34,1014.917578,6.388385e+07
2,2024-10-08 02:00:00,62457.34,62665.39,62115.15,62218.75,996.454240,6.217570e+07
3,2024-10-08 03:00:00,62218.75,62580.00,62150.93,62546.53,776.026527,4.842057e+07
4,2024-10-08 04:00:00,62546.53,62725.40,62312.22,62632.78,813.166438,5.084945e+07
5,2024-10-08 05:00:00,62632.78,62788.56,62412.78,62779.38,711.515810,4.452361e+07
6,2024-10-08 06:00:00,62779.38,62818.51,62545.36,62633.88,506.597669,3.174774e+07
7,2024-10-08 07:00:00,62633.88,62782.56,62530.00,62684.52,492.339112,3.085980e+07
8,2024-10-08 08:00:00,62684.52,62728.41,62295.33,62512.14,784.395778,4.900929e+07
9,2024-10-08 09:00:00,62512.14,62527.20,62189.03,62506.40,992.950832,6.193083e+07
10,2024-10-08 10:00:00,62506.40,62506.40,61994.35,62312.12,1202.155928,7.481421e+07
11,2024-10-08 11:00:00,62312.12,62441.39,62185.85,62413.33,948.120556,5.909192e+07
12,2024-10-08 12:00:00,62413.33,62592.55,62298.77,62537.29,795.902579,4.968724e+07
13,2024-10-08 13:00:00,62537.29,62593.00,62405.13,62520.72,822.539455,5.141715e+07
14,2024-10-08 14:00:00,62520.72,62667.48,62464.93,62630.21,740.272516,4.631127e+07
15,2024-10-08 15:00:00,62630.21,62675.26,62414.31,62439.20,843.789675,5.278357e+07
16,2024-10-08 16:00:00,62439.20,63044.51,62323.30,63021.37,1515.135745,9.497844e+07
17,2024-10-08 17:00:00,63021.37,63202.67,62162.69,62779.32,1496.875426,9.375846e+07
18,2024-10-08 18:00:00,62779.32,62835.50,61863.10,62288.17,1319.223297,8.227669e+07
19,2024-10-08 19:00:00,62288.17,62605.12,62034.87,62568.58,1085.074658,6.762175e+07
20,2024-10-08 20:00:00,62568.58,62574.76,62071.68,62390.81,852.037094,5.307503e+07
21,2024-10-08 21:00:00,62390.81,62526.09,61924.06,62114.58,777.219291,4.834566e+07
22,2024-10-08 22:00:00,62114.58,62354.10,61857.13,62343.41,782.236488,4.855799e+07

In [3]:
az.crypto.candles('BTC/USDT', provider="bybit", interval="1d", start_date="2024-10-07", end_date="2024-10-08").to_df()

,date,open,high,low,close,volume,value
0,2024-10-06 03:00:00,62059.37,62983.78,61814.96,62824.80,9037.917928,5.640279e+08
1,2024-10-07 03:00:00,62824.80,64470.19,62115.15,62218.75,19762.195435,1.252398e+09
2,2024-10-08 03:00:00,62218.75,63202.67,61857.13,62343.72,18257.581886,1.140061e+09